## Set to -1 in order to disable configuration update reminders
config-version: 6




timer:
  ## The amount of seconds everyone starts off with
  ## default: 86400 (24 hours)
  start-time-in-seconds: 86400

  ## When set to true, players who join the server late will have their time set to a fair
  ## amount automatically (same amount of time as the person who currently has the most)
  balanced-time-for-latecomers: true

  ## The amount of seconds a player will have after being revived
  ## This only applies if recipes.revival-item.enabled is set to true
  ## default: 10800 (3 hours)
  seconds-on-revival: 10800

  ## When set to true, offline players will not lose time.
  ignore-offline-players: false




boogeyman:
  ## The amount of time it takes for the boogeyman to actually be rolled
  ## after running the command
  roll-delay-in-minutes: 10

  ## Determines whether reminders will be sent out to everyone.
  ## I recommend disabling this if the roll-delay-in-minutes is set to less than 10.
  reminders: true

  ## The maximum and minimum amount of boogeymen that are able to be chosen
  ## Set both to the same value to force a certain amount
  amount-min: 1
  amount-max: 1

  ## The amount of time gained when a boogeyman secures a kill (in seconds)
  time-gain-on-boogey-kill: 3600

  ## The amount of time lost when someone gets killed by a boogeyman (in seconds)
  time-lost-on-boogey-death: 7200

  ## Determines whether red names can be chosen as a boogeyman
  red-boogeymen: true




penalties:
  ## The amount of time players lose upon dying (in seconds)
  time-lost-on-death: 3600

  ## Determines whether players will lose time when killed by someone with the same
  ## name colour as them (doesn't apply to red names or boogeyman deaths)
  subtract-time-on-death-same-colour: true




rewards:
  ## The amount of time players upon killing someone (in seconds)
  time-gain-on-kill: 1800

  ## Determines whether players will receive time when they kill someone with
  ## the same name colour as them (doesn't apply to red names or boogeymen)
  add-time-on-kill-same-colour: true




name-colour-thresholds:
  ## The amount of time the player needs to have less than in order to become a red name (in seconds)
  ## default: 28800 (8 hours)
  red-name: 28800

  ## The amount of time the player needs to have less than in order to become a yellow name (in seconds)
  ## default: 57600 (16 hours)
  yellow-name: 57600

  ## The amount of time the player needs to have less than in order to become a green name (in seconds)
  ## Only applies if dark-green-names is set to true
  ## default: 86400 (24 hours)
  green-name: 86400

  ## Determines whether people with more time than specified in the field above will have a dark green name
  dark-green-names: false




## Please note that the following settings only get applied while in survival mode. ###################### !!! ######################
recipes:
  ## The following five settings determine whether the listed items are craftable, able to be picked up, or able to be interacted with in an inventory
  helmets-unobtainable: true
  bookshelves-unobtainable: true
  netherite-unobtainable: false
  golden-apples-unobtainable: false
  enchanted-golden-apples-unobtainable: true

  ## Creates a new recipe for tnt which replaces most of the gunpowder required with paper
  paper-tnt: true

  ## Determines whether saddles and/or name tags are craftable
  craftable-saddle: true
  craftable-name-tag: true
  craftable-slimeball: false

  ## Determines whether an item with the ability to revive players can be crafted
  ## For the recipe, please make sure to use the correct enum names for materials
  ## https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  revival-item:
    enabled: false
    ## Determines whether the clock should be removed from the player's inventory after being used
    consume-on-usage: true
    ## Determines whether revived players should be teleported to the main world's spawn location (level-name in server.properties)
    teleport-to-world-spawn: true
    row1: BLAZE_ROD DIAMOND_BLOCK BLAZE_ROD
    row2: REDSTONE_BLOCK CLOCK REDSTONE_BLOCK
    row3: GOLDEN_APPLE DIAMOND_BLOCK GOLDEN_APPLE




## Please note that the following settings only get applied while in survival mode. ###################### !!! ######################
enchantment-table:
  craftable: true

  ## I recommend only changing the following two settings if you don't want the table to be craftable!
  breakable: true

  ## Makes every enchantment table on the ground immortal and unable to be despawned when enabled.
  ## E.x. it won't burn in lava and can't be blown up.
  indestructible-on-drop: false




## Determines whether enchantments will be nerfed when applied to an item.
anvil:
  stacking-nerf: false
  level-limit: 2




## You may whitelist potions by adding their enum name to the list.
## For help on how a potion's name should be spelled, refer to the wiki: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html
## Please note that the following settings only get applied while in survival mode. ###################### !!! ######################
potion-whitelist:
  enabled: false
  list:
    - WATER
    - AWKWARD
    - MUNDANE
    - INVISIBILITY
    - SPEED
    - FIRE_RESISTANCE
    - NIGHT_VISION
    - JUMP
    - WATER_BREATHING




## Make sure to use only valid enum names. For help, refer to the following wiki page:
## https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
## (You may use CTRL+F to find the sound you want easily)
## Setting a value to null will disable the sound effect
sound-effects:
  enabled: true
  boogeyman-chosen: ENTITY_ENDER_DRAGON_GROWL
  boogeyman-failed: ENTITY_ENDER_DRAGON_GROWL
  boogeyman-cured: ENTITY_VILLAGER_YES
  boogeyman-not-chosen: ENTITY_VILLAGER_YES
  countdown: BLOCK_NOTE_BLOCK_HAT
  timer-begun: ITEM_GOAT_HORN_SOUND_2




custom-chat-format:
  enabled: false
  ## Make sure to include 'player' and 'message' in the format, as they are placeholders!
  format: "player: message"




other:
  ## Determines whether lightning will be struck at the last location of the player when they run out of time.
  ## The lightning strike will not deal any player/environmental damage.
  lightning-strike-on-final-death: true

  ## Quick command to find out whether you're the boogeyman
  am-i-the-boogeyman-command: true

  ## Determines whether a message will be sent out to all other admins whenever someone runs a command
  ## Example: [Alex: Added 30 minutes to Steve's timer]
  command-feedback: true

  ## Determines whether the plugin should print out an update reminder upon every startup/reload
  ## whenever there's one available
  plugin-update-reminders: true