name: LimitedLife
version: '${project.version}'
main: me.rowyourboat.limitedlife.LimitedLife
api-version: 1.19
author: RowwYourBoat
description: A recreation of the plugin/mod used in the official Limited Life series by Grian!
website: https://github.com/RowwYourBoat
softdepend:
  - PlaceholderAPI

commands:
  limitedlife:
    permission: limitedlife.admin
    description: Holder of all sub-commands.
    usage: /lf help
    aliases:
      - lf
  amitheboogeyman:
    permission: limitedlife.amitheboogeyman
    description: Shows you whether you're the boogeyman.
    usage: /amitheboogeyman

permissions:
  limitedlife.admin:
    default: op
    description: Grants permission to all sub-commands.
  limitedlife.amitheboogeyman:
    default: true
    description: Grants permission to run the /amitheboogeyman command.